### ISSUE TITLE
zdmo_cl_rap_generator_setup code error in on-premise 2020

### ISSUE THREAD

**Issue by skyskai** [SAP-samples/cloud-abap-rap#12]
The code in CREATE_SERVICE_BINDING in zdmo_cl_rap_generator_setup on-premise 2020 is commented out.
So, if I uncomment and activate the code, an error occurs in the code below.
` DATA(specification_srvb) = mo_srvb_put_operation->for-srvb->add_object(   service_binding_name
                                        )->set_package( package_name_of_rap_generator
                                        )->create_form_specification( ).
`
Error Text
`"FOR" is not a reference variable.`

When I looked at TS_API among the variable definitions of IF_XCO_GEN_O_MASS_PUT, it was as follows.
`  BEGIN OF ts_api,
      bdef TYPE REF TO if_xco_gen_bdef_o_m_put_sctn,
      clas TYPE REF TO if_xco_gen_clas_o_m_put_sctn,
      ddls TYPE REF TO if_xco_gen_ddls_o_m_put_sctn,
      ddlx TYPE REF TO if_xco_gen_ddlx_o_m_put_sctn,
      doma TYPE REF TO if_xco_gen_doma_o_m_put_sctn,
      dtel TYPE REF TO if_xco_gen_dtel_o_m_put_sctn,
      intf TYPE REF TO if_xco_gen_intf_o_m_put_sctn,
      srvd TYPE REF TO if_xco_gen_srvd_o_m_put_sctn,
      tabl TYPE ts_tabl,
      ttyp TYPE REF TO if_xco_gen_ttyp_o_m_put_sctn,
    END OF ts_api.`

**Comment by anfisc** [comment]
I have stopped supporting providing a branch for 2020 since it is too much work to support this release unfortunately.
