### ISSUE TITLE
Read me file: Link Correction

### ISSUE THREAD

**Issue by umtyzc** [SAP-samples/cloud-abap-rap#13]
Hi Andre, thanks for your amazing rap generator. I noticed a little mistake. These links not work,

**Not work:**
"And for on premise systems you have to use the appropriate branch on-premise-2020 https://github.com/SAP-samples/cloud-abap-rap/tree/On-Premise-2020 or on-premise-2021 https://github.com/SAP-samples/cloud-abap-rap/tree/On-Premise-2020" 

**Correct:**

And for on premise systems you have to use the appropriate branch on-premise-2020 https://github.com/SAP-samples/cloud-abap-rap/tree/on-premise-2020 or on-premise-2021 https://github.com/SAP-samples/cloud-abap-rap/tree/on-premise-2021

**Comment by anfisc** [comment]
fixed
