### ISSUE TITLE
Error following RAP generator installation, generator setup

### ISSUE THREAD

**Issue by fleischr** [SAP-samples/cloud-abap-rap#14]
Stuck on step 6. "Run the class zdmo_cl_rap_generator_setup. This class generates the following objects"

I get a message 
![image](https://user-images.githubusercontent.com/5488489/218191238-4d4cf987-c54d-4eb3-8b72-160863a899bb.png)

Check the class texts - they appear missing
![image](https://user-images.githubusercontent.com/5488489/218191425-28e6c079-5405-4e01-877c-9e53f39e20f4.png)

Tried re-pulling the repo a few times with no luck. Can you advise on the class texts I need for ZDMO_CL_RAP_GENERATOR_SETUP?

**Comment by anfisc** [comment]
Not sure what has happened here. (Sorry for my late reply). Which branch have you tried? And can you maybe try again ? I have published several updates since february.
