### ISSUE TITLE
2021 Branch containes 2022 code - Source cannot be activated

### ISSUE THREAD

**Issue by BenjaminWeisheit** [SAP-samples/cloud-abap-rap#15]
Some files cannot be activated in an 2021 system. The 2021 branch contains code that seems to be intended for a 2022 on prem system. 

![Ze1yZVSeHi](https://user-images.githubusercontent.com/77887261/221610229-dee69505-5189-46e5-8170-a53afbd6f5b4.png)

And some classes cannot be activated due to syntax errors.

![yWawo9Likx](https://user-images.githubusercontent.com/77887261/221611434-832f4a6e-641e-4403-a610-ba94c81ee1c3.png)

**Comment by huetterm** [comment]
Same to me. I replaced localy several times with:
```
      ASSIGN COMPONENT component_permission_request-name of STRUCTURE permission_request-%field to FIELD-SYMBOL(<lv_field>).
      <lv_field> = if_abap_behv=>mk-on.
*      permission_request-%field-(component_permission_request-name) = if_abap_behv=>mk-on.
```

**Comment by anfisc** [comment]
This has been fixed. In the branch 2021 the respective code is commented out so that the classes can be activate
