### ISSUE TITLE
2021 on Premise Class Name mismatch?

### ISSUE THREAD

**Issue by Sapdevipex** [SAP-samples/cloud-abap-rap#16]
Hello,

This generator was of great help in BTP ABAP environment. I am trying to use this for a 2021 on premise and noticed that one of the filenames references a different class.

I could get it to work after changing the name. ZDMO_CL_RAP_GEN_ENV_ON_PREM  ===> zdmo_cl_rap_xco_on_prem_lib  

![image](https://user-images.githubusercontent.com/129340727/228703630-8edea16d-ed6b-4121-b1d6-bb255b78780b.png)

Also noticed that 2021 did not support keyword "transactional_interface" in Proj view ZDMO_I_RAPG_ProjectTP .

![image](https://user-images.githubusercontent.com/129340727/228703927-6853c138-c02f-4a3d-bb6e-57c11b988d75.png)

This is an FYI post because fixing these made it work.

**Comment by Sapdevipex** [comment]
Hello @Juthbe  ,

Would you replace the "Transactional_interface" with "Transactional_query?", then use another pull to check what comes in diff?

**Comment by anfisc** [comment]
There is a new version available. Please try it out. I would assume it has fixed the issues you have described
