### ISSUE TITLE
Parent UUID - Checks for DOMAIN to of UUID and throws error

### ISSUE THREAD

**Issue by jagdishc** [SAP-samples/cloud-abap-rap#2]
ZCL_RAP_NODE class  - Line number 1406, checks for the domain of parent uuid. Although, the table contains correct UUID, it throws an exception as the DOMAIN is not filled in @lt_fields(possibly gone wrong in method read_domain).

**Comment by anfisc** [comment]
Is it still an issue?

**Comment by anfisc** [comment]
not relevant anymore
