### ISSUE TITLE
Missing ZDMO_UI_RAPG_PROJECT_O4 in on-prem-2022 branch

### ISSUE THREAD

**Issue by mem1b** [SAP-samples/cloud-abap-rap#20]
For the on-prem-2022 branch no ZDMO_UI_RAPG_PROJECT_O4 is available as mentioned in the readme, only the O2 is available.

**Comment by anfisc** [comment]
I switched to use a OData V2 service binding instead. So if you run the setup class a V2 binding ZDMO_UI_RAPG_PROJECT_O2 will be generated instead. But thanks for the hint to update the readme.
