### ISSUE TITLE
Error on importing objects on OnPrem 2020 FPS01

### ISSUE THREAD

**Issue by marianfoo** [SAP-samples/cloud-abap-rap#5]
Hi @anfisc,
got following errors importing the objects from On-Premise-2020 branch with ababGit
System is `S/4HANA On Premise 2020 FPS01`:
## Object Type not supported
![image](https://user-images.githubusercontent.com/13335743/154010337-74be4b59-4769-4771-8081-d93ff34e320f.png)

## Error on activating behavior definition
https://github.com/SAP-samples/cloud-abap-rap/blob/dec6b41b89309b64e7e6676ebe67d4bebf16ea1e/src/zdmo_i_rapgeneratorbo.bdef.asbdef#L38-L43
![image](https://user-images.githubusercontent.com/13335743/154010392-f382925a-26f7-4dde-ac4b-1eb64e7909d5.png)

Can i help you with more?

**Comment by anfisc** [comment]
Sorry, I published it to early for 2020 and I am not yet ready with all the adjustments for 2020. But I am on it.

**Comment by marianfoo** [comment]
@anfisc all good, thought so, if you need someone to test just let me know
