### ISSUE TITLE
Error while Pull via offline repo

### ISSUE THREAD

**Issue by anupd007** [SAP-samples/cloud-abap-rap#6]
Hello Team , 
Attached error when I make a pull request for branch On-prem 2021 branch
![Error Snapshot](https://user-images.githubusercontent.com/72448208/154635071-b6fee352-0740-4c6c-9088-6d707efa0b87.PNG)
my system details 
![system details](https://user-images.githubusercontent.com/72448208/154635180-36a6545f-3b72-4b73-971b-67bdfb5d67aa.PNG)

**Comment by marianfoo** [comment]
Hi @anupd007
why do you pull 2021 when you are on 2020?
Andre told me 2020 is not ready yet. He is still working on it.

**Comment by selvamohankumar** [comment]
Even 2020 version fails on same.

**Comment by mantrisagar** [comment]
I am on version 2021 but still getting same errors as @anupd007.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/38910687/220439565-01374b12-56d0-4424-846d-dff279f73064.png">

<img width="375" alt="image" src="https://user-images.githubusercontent.com/38910687/220440118-8f99ad72-6c3a-4e7a-be78-da1e98268515.png">

Also getting dump on below line while trying to create project,
<img width="461" alt="image" src="https://user-images.githubusercontent.com/38910687/220440386-26b3274c-2485-4cae-826f-a8db7697e4ed.png">

@anfisc

**Comment by anfisc** [comment]
I have stopped the support of 2020 since it is to cumbersome to maintain this codeline (too much 2020 specific changes needed)
